import type { Theme } from "./theme.js";

/**
 * Theme presets. Each is a *complete* set of tokens over the same design system —
 * a preset is a starting point the generator can then override (e.g. swap the
 * palette for one extracted from the brand's logo). Fonts use safe system-stack
 * fallbacks so an exported site renders even before web fonts load.
 */

export const THEME_PRESETS = [
  "luxury",
  "minimal",
  "modern",
  "clinical",
  "fashion",
  "premium-dark",
  "premium-light",
] as const;

export type ThemePresetKey = (typeof THEME_PRESETS)[number];

const SANS = "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif";
const SERIF = "'Fraunces', 'Playfair Display', Georgia, serif";
const GROTESK = "'Space Grotesk', 'Inter', system-ui, sans-serif";

export const PRESET_THEMES: Record<ThemePresetKey, Theme> = {
  modern: {
    preset: "modern",
    colors: {
      primary: "#1f6feb",
      primaryForeground: "#ffffff",
      secondary: "#0d1b2a",
      secondaryForeground: "#ffffff",
      accent: "#f4a261",
      accentForeground: "#1b1b1b",
      background: "#ffffff",
      foreground: "#101418",
      surface: "#f6f8fa",
      surfaceForeground: "#101418",
      muted: "#eef1f4",
      mutedForeground: "#5b6570",
      border: "#e1e6ea",
      success: "#1a7f52",
      warning: "#b7791f",
      error: "#c0392b",
    },
    typography: { headingFont: SANS, bodyFont: SANS, headingWeight: 700, bodyWeight: 400, scale: 1.25 },
    layout: {
      radius: 10,
      density: "comfortable",
      buttonStyle: "solid",
      cardStyle: "bordered",
      headerStyle: "classic",
      footerStyle: "rich",
      containerWidth: 1280,
    },
  },
  luxury: {
    preset: "luxury",
    colors: {
      primary: "#0b0b0c",
      primaryForeground: "#f7f3ea",
      secondary: "#8a6d3b",
      secondaryForeground: "#ffffff",
      accent: "#c8a951",
      accentForeground: "#0b0b0c",
      background: "#faf7f2",
      foreground: "#161412",
      surface: "#ffffff",
      surfaceForeground: "#161412",
      muted: "#efe9df",
      mutedForeground: "#6b6157",
      border: "#e3dccf",
      success: "#3f7d5b",
      warning: "#9c6f1c",
      error: "#a23b2e",
    },
    typography: { headingFont: SERIF, bodyFont: SANS, headingWeight: 600, bodyWeight: 400, scale: 1.333 },
    layout: {
      radius: 2,
      density: "comfortable",
      buttonStyle: "outline",
      cardStyle: "flat",
      headerStyle: "centered",
      footerStyle: "rich",
      containerWidth: 1280,
    },
  },
  minimal: {
    preset: "minimal",
    colors: {
      primary: "#111111",
      primaryForeground: "#ffffff",
      secondary: "#333333",
      secondaryForeground: "#ffffff",
      accent: "#111111",
      accentForeground: "#ffffff",
      background: "#ffffff",
      foreground: "#111111",
      surface: "#fafafa",
      surfaceForeground: "#111111",
      muted: "#f2f2f2",
      mutedForeground: "#666666",
      border: "#e6e6e6",
      success: "#1a7f52",
      warning: "#a6791f",
      error: "#c0392b",
    },
    typography: { headingFont: SANS, bodyFont: SANS, headingWeight: 600, bodyWeight: 400, scale: 1.2 },
    layout: {
      radius: 0,
      density: "compact",
      buttonStyle: "outline",
      cardStyle: "flat",
      headerStyle: "minimal",
      footerStyle: "simple",
      containerWidth: 1200,
    },
  },
  clinical: {
    preset: "clinical",
    colors: {
      primary: "#0e7c86",
      primaryForeground: "#ffffff",
      secondary: "#123c4a",
      secondaryForeground: "#ffffff",
      accent: "#37b3a7",
      accentForeground: "#06121a",
      background: "#ffffff",
      foreground: "#0f1c22",
      surface: "#f2fafb",
      surfaceForeground: "#0f1c22",
      muted: "#e6f2f4",
      mutedForeground: "#4d6771",
      border: "#d3e5e8",
      success: "#1a8f5f",
      warning: "#b07d19",
      error: "#c0392b",
    },
    typography: { headingFont: SANS, bodyFont: SANS, headingWeight: 600, bodyWeight: 400, scale: 1.2 },
    layout: {
      radius: 8,
      density: "comfortable",
      buttonStyle: "solid",
      cardStyle: "bordered",
      headerStyle: "classic",
      footerStyle: "simple",
      containerWidth: 1280,
    },
  },
  fashion: {
    preset: "fashion",
    colors: {
      primary: "#d6336c",
      primaryForeground: "#ffffff",
      secondary: "#1b1b1b",
      secondaryForeground: "#ffffff",
      accent: "#ff922b",
      accentForeground: "#1b1b1b",
      background: "#ffffff",
      foreground: "#161616",
      surface: "#fdf6f8",
      surfaceForeground: "#161616",
      muted: "#f6edf1",
      mutedForeground: "#6a5b62",
      border: "#efdfe6",
      success: "#1a7f52",
      warning: "#b7791f",
      error: "#c0392b",
    },
    typography: { headingFont: GROTESK, bodyFont: SANS, headingWeight: 700, bodyWeight: 400, scale: 1.333 },
    layout: {
      radius: 16,
      density: "comfortable",
      buttonStyle: "pill",
      cardStyle: "elevated",
      headerStyle: "classic",
      footerStyle: "rich",
      containerWidth: 1360,
    },
  },
  "premium-dark": {
    preset: "premium-dark",
    colors: {
      primary: "#c8a951",
      primaryForeground: "#0b0b0c",
      secondary: "#e7e2d6",
      secondaryForeground: "#0b0b0c",
      accent: "#d9b968",
      accentForeground: "#0b0b0c",
      background: "#0d0f12",
      foreground: "#f2efe9",
      surface: "#16191d",
      surfaceForeground: "#f2efe9",
      muted: "#1e2227",
      mutedForeground: "#a4a9b0",
      border: "#2a2f36",
      success: "#4cae83",
      warning: "#d0a34a",
      error: "#e06552",
    },
    typography: { headingFont: SERIF, bodyFont: SANS, headingWeight: 600, bodyWeight: 400, scale: 1.333 },
    layout: {
      radius: 6,
      density: "comfortable",
      buttonStyle: "solid",
      cardStyle: "elevated",
      headerStyle: "centered",
      footerStyle: "rich",
      containerWidth: 1280,
    },
  },
  "premium-light": {
    preset: "premium-light",
    colors: {
      primary: "#2b2f36",
      primaryForeground: "#ffffff",
      secondary: "#b08d57",
      secondaryForeground: "#ffffff",
      accent: "#b08d57",
      accentForeground: "#ffffff",
      background: "#fbfaf8",
      foreground: "#1c1f24",
      surface: "#ffffff",
      surfaceForeground: "#1c1f24",
      muted: "#f0eee9",
      mutedForeground: "#5e6470",
      border: "#e6e2da",
      success: "#1a7f52",
      warning: "#a6791f",
      error: "#b23a2c",
    },
    typography: { headingFont: SERIF, bodyFont: SANS, headingWeight: 600, bodyWeight: 400, scale: 1.25 },
    layout: {
      radius: 4,
      density: "comfortable",
      buttonStyle: "solid",
      cardStyle: "bordered",
      headerStyle: "classic",
      footerStyle: "rich",
      containerWidth: 1280,
    },
  },
};

export function getPreset(key: string): Theme {
  return PRESET_THEMES[(key as ThemePresetKey) in PRESET_THEMES ? (key as ThemePresetKey) : "modern"];
}

export const PRESET_LABELS: Record<ThemePresetKey, string> = {
  luxury: "Luxury",
  minimal: "Minimal",
  modern: "Modern",
  clinical: "Clinical",
  fashion: "Fashion",
  "premium-dark": "Premium Dark",
  "premium-light": "Premium Light",
};
